apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmailer
  namespace: openmailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmailer
  template:
    metadata:
      labels:
        app: openmailer
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: openmailer
        image: parthsinha90/openmailer:arm64
        ports:
        - containerPort: 8000
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: openmailer-secret
              key: APP_KEY
        - name: RUN_MIGRATIONS
          value: "true"
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "true"
        volumeMounts:
        - name: storage
          mountPath: /var/www/html/storage
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        # Add startup probe to give more time for initialization
        startupProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: openmailer-storage